export { default as Login } from "./login";
export { default as SignUp } from "./sign-up";
export { default as Meals } from "./meals";
export { default as MealDetails } from "./meal-details";
export { default as PostMeal } from "./post-meal";
export { default as Profile } from "./profile";
export { default as EditProfile } from "./edit-profile";
export { default as Favorites } from "./favorites";
export { default as Languages } from "./languages";
